name: CI

on:
  pull_request:
    branches:
    - main

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # may as well use 3.11 as it's faster
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff black darglint
    - name: Format with black
      run: |
        python -m black --check .
    - name: Lint with ruff
      run: |
        ruff check --format=github .
    - name: Lint with darglint
      run: |
        darglint --verbosity 2 --docstring-style sphinx -z long conduit

  test_minimal_dependencies:
    needs: [linters]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    # We are verifying here that it's possible to to import `EcoacousticsDataModule`
    # when basically only the audio dependencies are installed.
    - name: Install minimal dependencies
      run: |
        poetry env use 3.8
        poetry install --no-interaction --no-root --with torch --without image --without hydra --without download --without logging --without dev
    - name: Verify audio datamodule can be imported
      run: |
        poetry run python -c "from conduit.data.datamodules.audio import EcoacousticsDataModule"
  ci_suite:
    needs: [linters]
    runs-on: ubuntu-latest
    steps:
    #----------------------------------------------
    #       check-out repo and set-up python
    #----------------------------------------------
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'poetry'
    #----------------------------------------------
    # install dependencies
    #----------------------------------------------
    - name: Install dependencies
      run: |
        poetry env use 3.8
        poetry install --no-interaction --no-root --with torch --with fair
    - name: Set python path for all subsequent actions
      run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH
    #----------------------------------------------
    # type check
    #----------------------------------------------
    - uses: jakebailey/pyright-action@v1
      with:
        # don't show warnings
        level: error
    #----------------------------------------------
    # run tests
    #----------------------------------------------
    - name: Test with pytest
      run: |
        poetry run python -m pytest -vv tests/
    # - name: Run configen
    #   run: |
    #     poetry run sh generate_confs.sh
